# Generated by Django 6.0.2 on 2026-03-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, db_column='profile_picture', default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
