# Generated by Django 6.0.2 on 2026-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_category_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet_requirement',
            field=models.CharField(choices=[('none', 'No Dietary Preference'), ('keto', 'Keto'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten-free', 'Gluten-Free')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='event_tag',
            field=models.CharField(choices=[('none', 'Standard Recipe'), ('birthday', 'Birthday'), ('mothers-day', "Mother's Day"), ('valentines-day', "Valentine's Day"), ('christmas', 'Christmas'), ('halloween', 'Halloween'), ('st-patricks', "St. Patrick's Day"), ('easter', 'Easter'), ('eid', 'Eid'), ('anniversary', 'Anniversary'), ('wedding', 'Wedding')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], default='dinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_photos/'),
        ),
    ]
